services:
  gs-api: 
    build:
      context: .
    image: gabrielegiannessi/gs-api:latest
    ports:
        - "8000:8000"
    volumes:
        - .:/app 

  frontend: 
    build:
      context: ./frontend
    image: gabrielegiannessi/gs-frontend:latest
    ports:
        - "4200:4200"
    